<?php
return ['messages'=>['<p style="text-align: center;">En breve nos pondremos
en <br>contacto
contigo,para <br>resolver tus dudas.</p>'=>'<p style="text-align: center;">En breu ens posarem a<br>contacte amb tu,per<br>resoldre els teus dubtes.</p>','<p style="text-align: center;">En breve nos pondremos en contacto<br />contigo, para resolver tus dudas.</p><p> </p><table class="widefat"><tbody><tr class="alternate"><td id="xyz_ips_vAlign">[xyz-ips snippet="thank-you-page-BOLSA-TRABAJO"]</td></tr></tbody></table>'=>'<p style="text-align: center;">En breu ens posarem en contacte<br>amb tu, per resoldre els teus dubtes.</p><p> </p><table class="widefat"><tbody><tr class="alternate"><td id="xyz_ips_vAlign">[xyz-ips snippet="thank-you-page-BOLSA-TRABAJO"]</td></tr></tbody></table>','<p style="text-align: center;">¡No te olvides de seguirnos en nuestras redes sociales!</p><p>[xyz-ips snippet="save-lead-aiko"]</p>'=>'<p style="text-align: center;">No t\'oblidis de seguir-nos a les nostres xarxes socials!</p><p>[xyz-ips snippet="save-lead-aiko"]</p>','<p style="text-align: center;">¡No te olvides de seguirnos<br> en nuestras redes sociales!</p>'=>'<p style="text-align: center;">No t\'oblidis de seguir-nos<br>a les nostres xarxes socials!</p>','<p><img class="alignnone wp-image-1213" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Logo_TheCorner_Subvencionado-300x47.png" alt="" width="167" height="18" /></p><p><img class="alignnone wp-image-1920" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Ok.png" alt="" width="52" height="53" /></p><p>¡Muchas gracias por interesarte en<br />nuestros cursos de formación subvencionada!</p>'=>'<p><img class="alignnone wp-image-1213" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Logo_TheCorner_Subvencionado-300x47.png" alt="" width="167" height="18"></p><p><img class="alignnone wp-image-1920" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Ok.png" alt="" width="52" height="53"></p><p>Moltes gràcies per interessar-te en<br>els nostres cursos de formació subvencionada!</p>','<p><img class="alignnone wp-image-1213" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Logo_TheCorner_Subvencionado-300x47.png" alt="" width="167" height="18"></p>
<p><img class="alignnone wp-image-1920" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Ok.png" alt="" width="52" height="53"></p>
<p>¡Muchas gracias por interesarte en<br>nuestra bolsa de trabajo!</p>'=>'<p><img class="alignnone wp-image-1213" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Logo_TheCorner_Subvencionado-300x47.png" alt="" width="167" height="18"></p>
<p><img class="alignnone wp-image-1920" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Ok.png" alt="" width="52" height="53"></p>
<p>Moltes gràcies per interessar-te en<br>la nostra borsa de treball!</p>','Separador'=>'Separador','Volver al inicio'=>'Tornar a l\'inici','editor-text-editor-12026dab'=>'<p style="text-align: center;">En breu ens posarem a<br>contacte amb tu,per<br>resoldre els teus dubtes.</p>','editor-text-editor-40701b06'=>'<p><img class="alignnone wp-image-1213" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Logo_TheCorner_Subvencionado-300x47.png" alt="" width="167" height="18"></p><p><img class="alignnone wp-image-1920" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Ok.png" alt="" width="52" height="53"></p><p>Moltes gràcies per interessar-te en<br>els nostres cursos de formació subvencionada!</p>','editor-text-editor-43d87808'=>'<p style="text-align: center;">No t\'oblidis de seguir-nos a les nostres xarxes socials!</p><p>[xyz-ips snippet="save-lead-aiko"]</p>','editor-text-editor-4a2a5ef1'=>'<p style="text-align: center;">No t\'oblidis de seguir-nos<br>a les nostres xarxes socials!</p>','editor-text-editor-6588f8c4'=>'<p><img class="alignnone wp-image-1213" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Logo_TheCorner_Subvencionado-300x47.png" alt="" width="167" height="18"></p>
<p><img class="alignnone wp-image-1920" src="https://cursosgratuitos.thecorner.es/wp-content/uploads/2022/02/Ok.png" alt="" width="52" height="53"></p>
<p>Moltes gràcies per interessar-te en<br>la nostra borsa de treball!</p>','editor-text-editor-6f950d89'=>'<p style="text-align: center;">En breu ens posarem en contacte<br>amb tu, per resoldre els teus dubtes.</p><p> </p><table class="widefat"><tbody><tr class="alternate"><td id="xyz_ips_vAlign">[xyz-ips snippet="thank-you-page-BOLSA-TRABAJO"]</td></tr></tbody></table>','text-button-259c74c9'=>'Tornar a l\'inici','text-button-3847a0c5'=>'Tornar a l\'inici','text-divider-38570843'=>'Separador','text-divider-e212e48'=>'Separador']];
